/* SemanticCompareScreen — ⭐ Semantic Document Comparison with 6 Categories & PDF Difference Report */
import { useState, useRef, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Sparkles, FileText, Download, Scale, Bot, RefreshCw, FileCheck } from 'lucide-react';
import { uploadFile } from '../../services/files';
import { compareDocuments } from '../../services/ai';
import api from '../../services/api';
import Toast from '../../components/ui/Toast';
import { useToast } from '../../hooks/useToast';
import './ai-screen.css';

const IMPORTANCE_COLORS = {
  HIGH: { bg: 'rgba(239, 68, 68, 0.1)', fg: '#EF4444', border: 'rgba(239, 68, 68, 0.3)' },
  MEDIUM: { bg: 'rgba(245, 158, 11, 0.1)', fg: '#F59E0B', border: 'rgba(245, 158, 11, 0.3)' },
  LOW: { bg: 'rgba(59, 130, 246, 0.1)', fg: '#3B82F6', border: 'rgba(59, 130, 246, 0.3)' },
};

const CATEGORY_ICONS = {
  Deadline: '🕒',
  Temporal: '🕒',
  Entity: '👤',
  Financial: '💰',
  Scope: '📋',
  Semantic: '📜',
  Structural: '🏗️',
  Textual: '✍️',
};

export default function SemanticCompareScreen() {
  const navigate = useNavigate();
  const location = useLocation();
  const fileInputARef = useRef(null);
  const fileInputBRef = useRef(null);
  const [fileA, setFileA] = useState(null);
  const [fileB, setFileB] = useState(null);
  const [running, setRunning] = useState(false);
  const [comparisonResult, setComparisonResult] = useState(null);
  const [error, setError] = useState(null);
  const [filterCategory, setFilterCategory] = useState('ALL');
  const [generatingPdf, setGeneratingPdf] = useState(false);
  const { toast, showToast, dismissToast } = useToast();

  useEffect(() => {
    if (location.state?.chainedFile) {
      setFileA(location.state.chainedFile);
      showToast('Loaded Document A from previous workflow', 'info');
    }
  }, [location.state, showToast]);

  async function handleCompare() {
    if (!fileA || !fileB) {
      showToast('Please select both Document A and Document B to compare', 'warning');
      return;
    }
    setRunning(true);
    setError(null);
    setComparisonResult(null);

    try {
      const [resA, resB] = await Promise.all([
        uploadFile(fileA),
        uploadFile(fileB),
      ]);
      const fileIdA = resA._id || resA.id;
      const fileIdB = resB._id || resB.id;

      const result = await compareDocuments(fileIdA, fileIdB);
      setComparisonResult(result);
      showToast('Semantic comparison completed!', 'success');
    } catch (err) {
      setError(err.message || 'Semantic comparison failed. Please check server AI configuration.');
    } finally {
      setRunning(false);
    }
  }

  function handleDownloadReport() {
    if (!comparisonResult) return;
    const reportText = `# Semantic Document Comparison Report
Generated by PaperKit

Document A: ${fileA?.name || 'Document A'}
Document B: ${fileB?.name || 'Document B'}
Semantic Similarity Score: ${comparisonResult.similarity_score}% (${comparisonResult.similarity_category})

## Executive Summary
${comparisonResult.summary || 'N/A'}

## Meaningful Changes Breakdown
${(comparisonResult.changes || []).map((c, i) => `
### ${i + 1}. [${c.importance || 'MEDIUM'}] ${c.category || 'General'}: ${c.description || ''}
- **Previous (Doc A):** ${c.previous || '—'}
- **New (Doc B):** ${c.new || '—'}
`).join('\n')}
`;
    const blob = new Blob([reportText], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `semantic_diff_${fileA?.name?.split('.')[0]}_vs_${fileB?.name?.split('.')[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function handleGenerateDifferencePdf() {
    if (!comparisonResult) return;
    setGeneratingPdf(true);
    try {
      const reportMarkdown = `# Semantic Document Comparison Report
Document A: ${fileA?.name || 'Document A'}
Document B: ${fileB?.name || 'Document B'}
Semantic Similarity Score: ${comparisonResult.similarity_score}% (${comparisonResult.similarity_category})

## Executive Summary
${comparisonResult.summary || 'N/A'}

## Meaningful Changes Breakdown
${(comparisonResult.changes || []).map((c, i) => `
### ${i + 1}. [${c.importance || 'MEDIUM'}] ${c.category || 'General'} Change: ${c.description || ''}
- **Previous (Document A):** ${c.previous || '—'}
- **New (Document B):** ${c.new || '—'}
`).join('\n')}
`;

      const res = await api.post('/ai/generate-report-pdf', {
        title: 'Semantic Difference Report',
        subtitle: `${fileA?.name || 'Doc A'} vs ${fileB?.name || 'Doc B'} (${comparisonResult.similarity_score}% Similarity)`,
        content: reportMarkdown,
      });

      const downloadUrl = res.data.download_url?.startsWith('http')
        ? res.data.download_url
        : `${import.meta.env.VITE_API_URL || 'https://paperkit-backend.onrender.com'}${res.data.download_url}`;

      window.open(downloadUrl, '_blank');
      showToast('Difference PDF generated and opened!', 'success');
    } catch (err) {
      showToast(err.message || 'Failed to generate Difference PDF', 'error');
    } finally {
      setGeneratingPdf(false);
    }
  }

  const filteredChanges = comparisonResult?.changes?.filter(c => {
    if (filterCategory === 'ALL') return true;
    return c.category?.toLowerCase() === filterCategory.toLowerCase();
  }) || [];

  return (
    <div className="ai-screen">
      {/* 2 Document Pickers */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '16px' }}>
        {/* Document A */}
        <div className="ai-screen__file-section" style={{ margin: 0 }}>
          <span className="ai-screen__file-label" style={{ fontWeight: 700, color: 'var(--color-primary)' }}>Document A (Original)</span>
          <button
            className={`ai-screen__file-picker${fileA ? ' ai-screen__file-picker--has-file' : ''}`}
            onClick={() => fileInputARef.current?.click()}
            id="compare-file-a-btn"
            style={{ padding: '12px' }}
          >
            <FileText size={18} className="ai-screen__file-icon" />
            <span className="ai-screen__file-name" style={{ fontSize: '12px' }}>
              {fileA ? fileA.name : 'Choose Doc A…'}
            </span>
          </button>
          <input
            ref={fileInputARef}
            type="file"
            accept=".pdf,application/pdf"
            style={{ display: 'none' }}
            onChange={e => { if (e.target.files?.[0]) { setFileA(e.target.files[0]); setComparisonResult(null); } }}
            id="compare-file-a-input"
          />
        </div>

        {/* Document B */}
        <div className="ai-screen__file-section" style={{ margin: 0 }}>
          <span className="ai-screen__file-label" style={{ fontWeight: 700, color: '#9333EA' }}>Document B (Updated)</span>
          <button
            className={`ai-screen__file-picker${fileB ? ' ai-screen__file-picker--has-file' : ''}`}
            onClick={() => fileInputBRef.current?.click()}
            id="compare-file-b-btn"
            style={{ padding: '12px' }}
          >
            <FileText size={18} className="ai-screen__file-icon" color="#9333EA" />
            <span className="ai-screen__file-name" style={{ fontSize: '12px' }}>
              {fileB ? fileB.name : 'Choose Doc B…'}
            </span>
          </button>
          <input
            ref={fileInputBRef}
            type="file"
            accept=".pdf,application/pdf"
            style={{ display: 'none' }}
            onChange={e => { if (e.target.files?.[0]) { setFileB(e.target.files[0]); setComparisonResult(null); } }}
            id="compare-file-b-input"
          />
        </div>
      </div>

      {/* Compare Button */}
      <div className="ai-screen__submit-area">
        <button
          className="ai-screen__submit-btn"
          onClick={handleCompare}
          disabled={running || !fileA || !fileB}
          id="compare-submit-btn"
          style={{ background: 'linear-gradient(135deg, #2563EB, #9333EA)' }}
        >
          {running ? (
            <>
              <span className="ai-screen__submit-spinner" />
              Comparing Meaning & Semantic Changes…
            </>
          ) : (
            <>
              <Scale size={18} />
              Compare Meaning with Semantic AI
            </>
          )}
        </button>
      </div>

      {/* Error */}
      {error && <div className="ai-screen__error">{error}</div>}

      {/* Loading state */}
      {running && (
        <div className="ai-screen__loading" style={{ marginTop: '20px' }}>
          <div className="ai-screen__loading-orb" style={{ background: 'linear-gradient(135deg, #2563EB, #9333EA)' }}>
            <Sparkles size={26} color="#fff" />
          </div>
          <p className="ai-screen__loading-text">Analyzing conceptual differences…</p>
          <p className="ai-screen__loading-sub">Classifying temporal, financial, semantic, and entity changes</p>
        </div>
      )}

      {/* Comparison Results */}
      {comparisonResult && !running && (
        <div style={{ marginTop: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Similarity score meter */}
          <div style={{ background: 'var(--color-surface)', padding: '16px', borderRadius: '16px', border: '1px solid var(--color-divider)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
              <span style={{ fontWeight: 600, fontSize: '14px' }}>Semantic Document Similarity</span>
              <span style={{ fontWeight: 800, fontSize: '18px', color: 'var(--color-primary)' }}>
                {comparisonResult.similarity_score || 85}%
              </span>
            </div>
            
            <div style={{ height: '8px', background: 'var(--color-divider)', borderRadius: '4px', overflow: 'hidden' }}>
              <div style={{
                height: '100%',
                width: `${comparisonResult.similarity_score || 85}%`,
                background: (comparisonResult.similarity_score || 85) > 75 ? '#10B981' : (comparisonResult.similarity_score || 85) > 45 ? '#F59E0B' : '#EF4444',
                transition: 'width 0.6s ease-out'
              }} />
            </div>

            <div style={{ marginTop: '8px', display: 'flex', justifyContent: 'space-between', fontSize: '12px', color: 'var(--color-text-secondary)' }}>
              <span>Classification: <strong>{comparisonResult.similarity_category || 'Similar'}</strong></span>
              <span>{(comparisonResult.changes || []).length} Meaningful Changes Detected</span>
            </div>

            {comparisonResult.summary && (
              <div style={{ marginTop: '12px', padding: '10px 14px', borderRadius: '10px', background: 'var(--color-primary-soft)', fontSize: '13px', color: 'var(--color-text)' }}>
                <strong>Summary:</strong> {comparisonResult.summary}
              </div>
            )}
          </div>

          {/* Category Filter Pills */}
          <div style={{ display: 'flex', gap: '6px', overflowX: 'auto', paddingBottom: '4px' }}>
            {['ALL', 'Temporal', 'Financial', 'Entity', 'Scope', 'Semantic', 'Structural', 'Textual'].map(cat => (
              <button
                key={cat}
                type="button"
                onClick={() => setFilterCategory(cat)}
                style={{
                  padding: '5px 10px',
                  borderRadius: '16px',
                  fontSize: '11px',
                  fontWeight: filterCategory === cat ? 700 : 500,
                  background: filterCategory === cat ? 'var(--color-primary)' : 'var(--color-surface)',
                  color: filterCategory === cat ? '#fff' : 'var(--color-text-secondary)',
                  border: '1px solid var(--color-divider)',
                  cursor: 'pointer',
                  whiteSpace: 'nowrap'
                }}
              >
                {cat === 'ALL' ? 'All Changes' : `${CATEGORY_ICONS[cat] || ''} ${cat}`}
              </button>
            ))}
          </div>

          {/* Meaningful changes list */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {filteredChanges.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '24px', background: 'var(--color-surface)', borderRadius: '12px', fontSize: '13px', color: 'var(--color-text-secondary)' }}>
                No changes found in category "{filterCategory}".
              </div>
            ) : (
              filteredChanges.map((change, idx) => {
                const impStyle = IMPORTANCE_COLORS[change.importance?.toUpperCase()] || IMPORTANCE_COLORS.MEDIUM;
                return (
                  <div
                    key={idx}
                    style={{
                      background: 'var(--color-surface)',
                      borderRadius: '14px',
                      padding: '14px',
                      border: `1px solid ${impStyle.border}`,
                      boxShadow: '0 2px 8px rgba(0,0,0,0.03)'
                    }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                        <span style={{ fontSize: '16px' }}>{CATEGORY_ICONS[change.category] || '🔍'}</span>
                        <span style={{ fontWeight: 700, fontSize: '13px' }}>MEANINGFUL CHANGE: {change.category || 'General'}</span>
                      </div>
                      <span style={{
                        fontSize: '10px',
                        fontWeight: 700,
                        padding: '2px 8px',
                        borderRadius: '10px',
                        background: impStyle.bg,
                        color: impStyle.fg,
                        border: `1px solid ${impStyle.border}`
                      }}>
                        {change.importance || 'HIGH'} IMPORTANCE
                      </span>
                    </div>

                    <p style={{ fontSize: '12px', color: 'var(--color-text-secondary)', marginBottom: '10px' }}>
                      {change.description}
                    </p>

                    {/* Side-by-Side Before vs After */}
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', fontSize: '12px' }}>
                      <div style={{ padding: '8px 10px', borderRadius: '8px', background: 'rgba(239, 68, 68, 0.05)', border: '1px solid rgba(239, 68, 68, 0.15)' }}>
                        <div style={{ fontSize: '10px', fontWeight: 700, color: '#EF4444', marginBottom: '3px' }}>DOCUMENT A (PREVIOUS)</div>
                        <div>{change.previous || '—'}</div>
                      </div>
                      <div style={{ padding: '8px 10px', borderRadius: '8px', background: 'rgba(16, 185, 129, 0.05)', border: '1px solid rgba(16, 185, 129, 0.15)' }}>
                        <div style={{ fontSize: '10px', fontWeight: 700, color: '#10B981', marginBottom: '3px' }}>DOCUMENT B (NEW)</div>
                        <div>{change.new || '—'}</div>
                      </div>
                    </div>
                  </div>
                );
              })
            )}
          </div>

          {/* ⭐ Smart Workflow Chaining options matching spec:
              Options: Download Comparison Report | Generate Difference PDF | Ask AI About Changes | Compare Another Document | Exit */}
          <div style={{ marginTop: '10px', padding: '14px', borderRadius: '14px', background: 'var(--color-surface)', border: '1px solid var(--color-divider)', display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <div style={{ fontSize: '12px', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--color-text-secondary)', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Sparkles size={14} color="var(--color-primary)" /> What would you like to do next?
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: '8px' }}>
              <button
                type="button"
                onClick={handleGenerateDifferencePdf}
                disabled={generatingPdf}
                className="common-result__action-card"
              >
                <div className="common-result__action-icon">
                  <FileCheck size={16} />
                </div>
                <p className="common-result__action-label">{generatingPdf ? 'Generating…' : 'Difference PDF'}</p>
                <p className="common-result__action-desc">Download styled PDF diff</p>
              </button>

              <button
                type="button"
                onClick={handleDownloadReport}
                className="common-result__action-card"
              >
                <div className="common-result__action-icon">
                  <Download size={16} />
                </div>
                <p className="common-result__action-label">Download Report</p>
                <p className="common-result__action-desc">Export .MD markdown</p>
              </button>

              <button
                type="button"
                onClick={() => navigate('/ai/ask', { state: { chainedFile: fileB, rawText: `Semantic Differences between Doc A and Doc B:\n${JSON.stringify(comparisonResult.changes)}` } })}
                className="common-result__action-card"
              >
                <div className="common-result__action-icon">
                  <Bot size={16} />
                </div>
                <p className="common-result__action-label">Ask AI on Changes</p>
                <p className="common-result__action-desc">Discuss differences</p>
              </button>

              <button
                type="button"
                onClick={() => { setComparisonResult(null); setFileA(null); setFileB(null); }}
                className="common-result__action-card"
              >
                <div className="common-result__action-icon">
                  <RefreshCw size={16} />
                </div>
                <p className="common-result__action-label">Compare Another</p>
                <p className="common-result__action-desc">Reset comparison</p>
              </button>
            </div>
          </div>
        </div>
      )}

      {!comparisonResult && !running && !error && (
        <div className="ai-screen__unavailable" style={{ opacity: 0.45 }}>
          <div className="ai-screen__unavailable-icon" style={{ background: 'var(--color-primary-soft)' }}>
            <Scale size={28} color="var(--color-primary)" />
          </div>
          <p className="ai-screen__unavailable-title">Semantic Document Comparison</p>
          <p className="ai-screen__unavailable-sub">PaperKit detects conceptual changes in deadlines, financial terms, parties, and scope beyond basic text diffing.</p>
        </div>
      )}

      <Toast key={toast?.key} message={toast?.message} type={toast?.type} onDismiss={dismissToast} />
    </div>
  );
}
