[pytest]
norecursedirs = scratch
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:fastapi.*:
    ignore::DeprecationWarning:starlette.*:
    ignore::DeprecationWarning:jose.*:
    ignore::DeprecationWarning:importlib._bootstrap.*:
    ignore::DeprecationWarning:pytest_asyncio.*:
